    

services:
  php:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0